FROM debian:bookworm
# WORKDIR /app
# COPY backend/config ./config
# COPY backend/static ./static
# COPY backend/public ./public
# COPY backend/.env ./.env
# COPY --from=builder /usr/src/app/target/release/backend /app/backend
RUN sed -i 's/deb.debian.org/mirrors.aliyun.com/g' /etc/apt/sources.list.d/debian.sources && \
    apt-get update \
    && apt-get install -y \
    nginx \
    vim \
    && rm -rf /var/lib/apt/lists/* \
CMD ["/app/backend"]